# Generated by Django 3.1.1 on 2021-03-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='drug',
        ),
    ]
