# Generated by Django 3.1.1 on 2021-02-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_auto_20210201_0806'),
        ('diseases', '0002_auto_20210201_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='drug',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='drugs.generic'),
        ),
    ]
