# Generated by Django 3.1.1 on 2021-03-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_auto_20210309_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
