# Generated by Django 3.1.1 on 2021-03-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_management_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='treatment_category',
            field=models.CharField(choices=[('Non-Drug Management', 'Non-Drug Management')], default='Non-Drug Management', max_length=100),
        ),
    ]
