# Generated by Django 3.1.1 on 2021-02-04 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drugs.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_drug', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('packaging', models.CharField(max_length=100)),
                ('units_per_pack', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='utilities.categories')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.facility')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.manufacturer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_preparation', to='drugs.preparation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=drugs.models.product_image_upload_to)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='users.facility')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='drugs.products')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
