# Generated by Django 3.1.1 on 2021-02-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0011_remove_wholesalevariations_source'),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='distributors',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
