# Generated by Django 3.1.1 on 2021-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='phone',
        ),
        migrations.AddField(
            model_name='distributor',
            name='phone1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='phone3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='physical_address',
            field=models.CharField(default='', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributor',
            name='postal_address',
            field=models.CharField(default='', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributor',
            name='website',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='distributors',
            field=models.ManyToManyField(blank=True, null=True, to='drugs.Distributor'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterModelTable(
            name='distributor',
            table='distributors',
        ),
    ]
