# Generated by Django 3.1.1 on 2021-03-09 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('diseases', '0002_remove_management_drug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraindications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.diseases')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraindications', to='users.facility')),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.generic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
