# Generated by Django 3.1.1 on 2021-03-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modeofactions',
            constraint=models.UniqueConstraint(fields=('generic', 'mode_of_action'), name='No repetion entries per generic'),
        ),
    ]
