# Generated by Django 3.1.1 on 2021-03-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20210310_2314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interactions',
            table=None,
        ),
    ]
