# Generated by Django 3.1.1 on 2021-02-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_productimages_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='units_per_pack',
            field=models.IntegerField(),
        ),
    ]
