# Generated by Django 3.1.1 on 2021-02-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        ('drugs', '0003_auto_20210204_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='465f718a-c645-4181-ad15-1957719f7640', on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='utilities.categories'),
            preserve_default=False,
        ),
    ]
