# Generated by Django 3.1.1 on 2021-02-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_auto_20210212_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='distributor',
            table=None,
        ),
    ]
