# Generated by Django 3.1.1 on 2021-03-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_auto_20210311_1345'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interactions',
            name='Drug cannot be contraindicated with itself',
        ),
    ]
