# Generated by Django 3.1.1 on 2021-03-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_auto_20210309_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraindications',
            name='condition',
        ),
        migrations.AddField(
            model_name='contraindications',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
