# Generated by Django 3.1.1 on 2021-03-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20210309_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='distributors',
        ),
    ]
