# Generated by Django 3.1.1 on 2021-02-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20210204_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.manufacturer'),
        ),
    ]
