# Generated by Django 3.1.1 on 2021-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20210212_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='postal_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
