# Generated by Django 3.1.1 on 2021-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20210311_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactions',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='interactions',
            constraint=models.UniqueConstraint(fields=('generic', 'contra_indicated'), name='Drug cannot be contraindicated with itself'),
        ),
    ]
