# Generated by Django 3.1.1 on 2021-02-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('drugs', '0005_auto_20210204_0229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('facility', 'title')},
        ),
    ]
