# Generated by Django 3.1.1 on 2021-03-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20210311_1346'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interactions',
            name='Drug cannot be contraindicated with itself',
        ),
        migrations.AlterUniqueTogether(
            name='interactions',
            unique_together={('generic', 'contra_indicated')},
        ),
    ]
