# Generated by Django 3.1.1 on 2021-03-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_remove_manufacturer_distributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='latin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
