# Generated by Django 3.1.1 on 2021-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20210212_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodysystem',
            name='category',
            field=models.CharField(choices=[('CHOICE1', 'CHOICE ONE'), ('CHOICE2', 'CHOICE TWO'), ('CHOICE3', 'CHOICE THREE')], default='CHOICE ONE', max_length=100),
        ),
        migrations.AddField(
            model_name='bodysystem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
