# Generated by Django 3.1.1 on 2021-02-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_auto_20210201_2328'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interactions',
            name='Drug cannot be contraindicated with itself',
        ),
    ]
