# Generated by Django 3.1.1 on 2021-03-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_auto_20210311_1349'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interactions',
            unique_together={('generic', 'contra_indicated', 'description')},
        ),
    ]
