# Generated by Django 3.1.1 on 2021-02-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_auto_20210215_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodysystem',
            name='entry',
            field=models.DateField(auto_now=True),
        ),
    ]
