# Generated by Django 3.1.1 on 2021-02-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_auto_20210201_2329'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interactions',
            constraint=models.UniqueConstraint(fields=('generic', 'contra_indicated'), name='Drug cannot be contraindicated with itself'),
        ),
    ]
