# Generated by Django 3.1.1 on 2021-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_auto_20210310_1142'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='indications',
            constraint=models.UniqueConstraint(fields=('generic', 'disease', 'dose'), name='Indications must be unique'),
        ),
    ]
