# Generated by Django 3.1.1 on 2021-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_auto_20210311_1702'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sideeffects',
            constraint=models.UniqueConstraint(fields=('generic', 'title', 'description'), name='Do not repeat entry for generic'),
        ),
    ]
