# Generated by Django 3.1.1 on 2021-02-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_bodysystem_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodysystem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bodysystem',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='bodysystem',
            name='is_active',
        ),
    ]
