# Generated by Django 3.1.1 on 2021-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_auto_20210216_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_prescription_only',
            field=models.BooleanField(default=False),
        ),
    ]
