# Generated by Django 3.1.1 on 2021-03-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_auto_20210312_1339'),
        ('drugs', '0009_auto_20210312_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_category', to='utilities.subcategories'),
        ),
    ]
