# Generated by Django 3.1.1 on 2021-02-02 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_cadres_cluster'),
        ('drugs', '0009_auto_20210202_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialConsiderations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialconsiderations', to='users.facility')),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_special_info', to='drugs.generic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SpecialCondiderations',
        ),
    ]
