# Generated by Django 3.1.1 on 2021-02-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_products_is_prescription_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sub_category',
        ),
    ]
