# Generated by Django 3.1.1 on 2021-02-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_auto_20210202_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precautions',
            name='title',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sideeffects',
            name='title',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialconsiderations',
            name='title',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
