# Generated by Django 3.1.1 on 2021-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_auto_20210307_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='physical_address',
            field=models.CharField(max_length=120),
        ),
    ]
