# Generated by Django 3.1.1 on 2021-03-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_auto_20210308_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraindications',
            name='title',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
