# Generated by Django 3.1.1 on 2021-02-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despatches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('despatch_confirmed', models.BooleanField(default=True)),
                ('receipt_confirmed', models.BooleanField(default=True)),
                ('courier_confirmed', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DESPATCHED', 'DESPATCHED'), ('RECEIVED', 'RECEIVED'), ('CANCELLED', 'CANCELLED')], max_length=100)),
                ('priority', models.CharField(choices=[('HIGH', 'HIGH PRIORITY'), ('NORMAL', 'NORMAL PRIORITY'), ('LOW', 'LOW PRIORITY')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_courier', to='entities.employees')),
                ('courier_confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_confirmed_by', to=settings.AUTH_USER_MODEL)),
                ('despatch_confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_confirmed_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatches', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_owner', to=settings.AUTH_USER_MODEL)),
                ('receipt_confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_confirmed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WholesaleProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('trade_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesaleproducts', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_owner', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_products', to='drugs.products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WholesaleVariations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('pack_quantity', models.IntegerField()),
                ('pack_buying_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pack_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=140, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesalevariations', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_owner', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.distributor')),
                ('wholesale_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_variation_product', to='wholesales.wholesaleproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailerAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_allowed', models.BooleanField(default=False)),
                ('placement_allowed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.employees')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retaileraccounts', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_account_owner', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_retail_facility', to='users.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requisitions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retailer_confirmed', models.BooleanField(default=True)),
                ('wholesaler_confirmed', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('HIGH', 'HIGH PRIORITY'), ('NORMAL', 'NORMAL PRIORITY'), ('LOW', 'LOW PRIORITY')], max_length=100)),
                ('payment_terms', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('PLACEMENT', 'PLACEMENT')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_owner', to=settings.AUTH_USER_MODEL)),
                ('retailer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitioning_account', to='wholesales.retaileraccounts')),
                ('wholesale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_facility', to='users.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequisitionItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_required', models.IntegerField()),
                ('quantity_issued', models.IntegerField()),
                ('quantity_pending', models.IntegerField()),
                ('quantity_paid', models.IntegerField()),
                ('quantity_unpaid', models.IntegerField()),
                ('retailer_confirmed', models.BooleanField(default=True)),
                ('wholesaler_confirmed', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitionitems', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_item_owner', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition', to='wholesales.requisitions')),
                ('wholesale_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_authority', to=settings.AUTH_USER_MODEL)),
                ('wholesale_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_wholesale', to='wholesales.wholesaleproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_owner', to=settings.AUTH_USER_MODEL)),
                ('wholesale_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_variation', to='wholesales.wholesalevariations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DespatchPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_terms', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('PLACEMENT', 'PLACEMENT')], max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('despatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_for_despatch', to='wholesales.despatches')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatchpayments', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_payment_owner', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_payment_method', to='payments.paymentmethods')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DespatchItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_issued', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('despatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_despatch', to='wholesales.despatches')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatchitems', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_item_owner', to=settings.AUTH_USER_MODEL)),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_despatch', to='wholesales.requisitions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='despatches',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_despatch', to='wholesales.requisitions'),
        ),
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('for_every', models.IntegerField()),
                ('get_free', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_owner', to=settings.AUTH_USER_MODEL)),
                ('wholesale_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_variation', to='wholesales.wholesalevariations')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
