# Generated by Django 3.1.1 on 2021-02-04 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_auto_20210204_0438'),
        ('users', '0002_auto_20210204_0501'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_products', to='drugs.products'),
        ),
        migrations.CreateModel(
            name='WholesaleVariations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pack_quantity', models.IntegerField()),
                ('pack_buying_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pack_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesalevariations', to='users.facility')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_purchases', to='wholesales.listings')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_owner', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_purchases', to='drugs.distributor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
