# Generated by Django 3.1.1 on 2021-02-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wholesales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retaileraccounts',
            name='retailer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_retail_facility', to='users.facility'),
        ),
    ]
