# Generated by Django 3.1.1 on 2021-02-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='wholesale_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_variation_discount', to='wholesales.wholesalevariations'),
        ),
    ]
