# Generated by Django 3.1.1 on 2021-02-07 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
        ('drugs', '__first__'),
        ('wholesales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleVariations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('pack_quantity', models.IntegerField()),
                ('pack_buying_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pack_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=140, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesalevariations', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_owner', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.distributor')),
                ('wholesale_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_variation_product', to='wholesales.wholesaleproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
