# Generated by Django 3.1.1 on 2021-02-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0002_wholesalevariations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuses',
            name='wholesale_product',
        ),
        migrations.RemoveField(
            model_name='discounts',
            name='wholesale_product',
        ),
        migrations.RemoveField(
            model_name='requisitionitems',
            name='wholesale_product',
        ),
        migrations.AddField(
            model_name='bonuses',
            name='wholesale_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_product_bonus', to='wholesales.wholesalevariations'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='wholesale_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_product_discount', to='wholesales.wholesalevariations'),
        ),
        migrations.AddField(
            model_name='requisitionitems',
            name='wholesale_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_wholesale', to='wholesales.wholesalevariations'),
        ),
    ]
