# Generated by Django 3.1.1 on 2021-02-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0002_bonuses_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
