# Generated by Django 3.1.1 on 2021-02-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0002_auto_20210207_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitions',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('PARTIALLY_DISPATCHED', 'PARTIALLY DISPATCHED'), ('FULLY_DISPATCHED', 'FULLY DISPATCHED'), ('CANCELLED', 'CANCELLED'), ('CLOSED', 'CLOSED')], default='PENDING', max_length=100),
        ),
    ]
