# Generated by Django 3.1.1 on 2021-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0002_discounts_wholesale_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitems',
            name='retailer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitionitems',
            name='wholesaler_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
