# Generated by Django 3.1.1 on 2021-02-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0003_auto_20210212_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionitems',
            old_name='quantity_issued',
            new_name='bonus_quantity',
        ),
        migrations.AddField(
            model_name='requisitionitems',
            name='quantity_invoiced',
            field=models.IntegerField(default=0),
        ),
    ]
