# Generated by Django 3.1.1 on 2021-02-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0003_requisitions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitems',
            name='quantity_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisitionitems',
            name='quantity_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisitionitems',
            name='quantity_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisitionitems',
            name='quantity_unpaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='retailer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='wholesaler_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
