# Generated by Django 3.1.1 on 2021-02-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_auto_20210204_0438'),
        ('wholesales', '0003_auto_20210204_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleproducts',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listing_products', to='drugs.products'),
            preserve_default=False,
        ),
    ]
