# Generated by Django 3.1.1 on 2021-02-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0003_auto_20210207_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionitems',
            name='wholesale_variation',
        ),
        migrations.AddField(
            model_name='requisitionitems',
            name='wholesale_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_wholesale', to='wholesales.wholesaleproducts'),
        ),
    ]
