# Generated by Django 3.1.1 on 2021-02-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0003_auto_20210211_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleproducts',
            name='trade_price',
        ),
    ]
