# Generated by Django 3.1.1 on 2021-02-08 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0004_auto_20210207_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionitems',
            old_name='wholesaler_confirmed',
            new_name='wholesale_confirmed',
        ),
        migrations.RemoveField(
            model_name='requisitionitems',
            name='wholesale_authority',
        ),
        migrations.AddField(
            model_name='requisitionitems',
            name='wholesale_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_authority', to=settings.AUTH_USER_MODEL),
        ),
    ]
