# Generated by Django 3.1.1 on 2021-02-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wholesales', '0004_auto_20210212_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retaileraccounts',
            name='retailer',
        ),
        migrations.AddField(
            model_name='retaileraccounts',
            name='wholesale',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='retail_account_wholesale', to='users.facility'),
            preserve_default=False,
        ),
    ]
