# Generated by Django 3.1.1 on 2021-02-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0004_auto_20210204_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wholesalevariations',
            old_name='listing',
            new_name='wholesale_product',
        ),
    ]
