# Generated by Django 3.1.1 on 2021-02-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0004_auto_20210207_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalevariations',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wholesalevariations',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonuses',
            name='wholesale_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_variation', to='wholesales.wholesalevariations'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='wholesale_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_variation', to='wholesales.wholesalevariations'),
        ),
    ]
