# Generated by Django 3.1.1 on 2021-02-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0005_auto_20210207_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='start_time',
            field=models.DateField(),
        ),
    ]
