# Generated by Django 3.1.1 on 2021-02-05 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210204_0501'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0005_auto_20210204_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalevariations',
            name='wholesale_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_variation_product', to='wholesales.wholesaleproducts'),
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_owner', to=settings.AUTH_USER_MODEL)),
                ('wholesale_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_product_discount', to='wholesales.wholesaleproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('for_every', models.IntegerField()),
                ('get_free', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_owner', to=settings.AUTH_USER_MODEL)),
                ('wholesale_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_product_bonus', to='wholesales.wholesaleproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
