# Generated by Django 3.1.1 on 2021-02-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0005_auto_20210207_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionitems',
            old_name='wholesale_confirmed',
            new_name='wholesaler_confirmed',
        ),
        migrations.RenameField(
            model_name='requisitionitems',
            old_name='wholesale_confirmed_by',
            new_name='wholesaler_confirmed_by',
        ),
    ]
