# Generated by Django 3.1.1 on 2021-02-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('wholesales', '0006_auto_20210207_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despatches',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despatch_courier', to='entities.employees'),
        ),
    ]
