# Generated by Django 3.1.1 on 2021-02-07 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0006_auto_20210207_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discounts',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='discounts',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='bonuses',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bonuses',
            name='start_time',
        ),
        migrations.AddField(
            model_name='bonuses',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 7, 17, 23, 25, 269553, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonuses',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 7, 17, 23, 35, 406245, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
