# Generated by Django 3.1.1 on 2021-02-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210204_0501'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0006_auto_20210204_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleproducts',
            name='trade_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Requisitions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retailer_confirmed', models.BooleanField(default=True)),
                ('wholesaler_confirmed', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('HIGH', 'HIGH PRIORITY'), ('NORMAL', 'NORMAL PRIORITY'), ('LOW', 'LOW PRIORITY')], max_length=100)),
                ('payment_terms', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('PLACEMENT', 'PLACEMENT')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_owner', to=settings.AUTH_USER_MODEL)),
                ('wholesale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_facility', to='users.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequisitionItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_required', models.IntegerField()),
                ('quantity_issued', models.IntegerField()),
                ('quantity_pending', models.IntegerField()),
                ('quantity_paid', models.IntegerField()),
                ('quantity_unpaid', models.IntegerField()),
                ('retailer_confirmed', models.BooleanField(default=True)),
                ('wholesaler_confirmed', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitionitems', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_item_owner', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition', to='wholesales.requisitions')),
                ('wholesale_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_wholesale', to='wholesales.wholesaleproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
