# Generated by Django 3.1.1 on 2021-02-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0006_auto_20210212_1126'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='retaileraccounts',
            constraint=models.UniqueConstraint(fields=('facility', 'wholesale'), name='Unique account per retailer'),
        ),
    ]
