# Generated by Django 3.1.1 on 2021-02-05 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210204_0501'),
        ('payments', '0001_initial'),
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0007_auto_20210205_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despatches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('despatch_confirmed', models.BooleanField(default=True)),
                ('receipt_confirmed', models.BooleanField(default=True)),
                ('courier_confirmed', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DESPATCHED', 'DESPATCHED'), ('RECEIVED', 'RECEIVED'), ('CANCELLED', 'CANCELLED')], max_length=100)),
                ('priority', models.CharField(choices=[('HIGH', 'HIGH PRIORITY'), ('NORMAL', 'NORMAL PRIORITY'), ('LOW', 'LOW PRIORITY')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_courier', to='entities.employees')),
                ('courier_confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_confirmed_by', to=settings.AUTH_USER_MODEL)),
                ('despatch_confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_confirmed_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatches', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_owner', to=settings.AUTH_USER_MODEL)),
                ('receipt_confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_confirmed_by', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_despatch', to='wholesales.requisitions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requisitionitems',
            name='wholesale_authority',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_authority', to='users.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DespatchPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_terms', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('PLACEMENT', 'PLACEMENT')], max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('despatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_for_despatch', to='wholesales.despatches')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatchpayment', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_payment_owner', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_payment_method', to='payments.paymentmethods')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DespatchItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_issued', models.IntegerField()),
                ('despatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_despatch', to='wholesales.despatches')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatchitems', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_item_owner', to=settings.AUTH_USER_MODEL)),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_despatch', to='wholesales.requisitions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
