# Generated by Django 3.1.1 on 2021-02-07 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '__first__'),
        ('users', '__first__'),
        ('wholesales', '0007_auto_20210207_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_allowed', models.BooleanField(default=False)),
                ('placement_allowed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.employees')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retaileraccount', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_account_owner', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_retail_facility', to='users.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requisitions',
            name='retailer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitioning_account', to='wholesales.retaileraccount'),
        ),
    ]
