# Generated by Django 3.1.1 on 2021-02-08 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0007_auto_20210208_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despatches',
            name='courier_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_confirmed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='despatches',
            name='despatch_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despatch_confirmed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='despatches',
            name='receipt_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_confirmed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
