# Generated by Django 3.1.1 on 2021-02-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0007_auto_20210212_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retaileraccounts',
            old_name='account_contact',
            new_name='retailer_contact',
        ),
        migrations.RenameField(
            model_name='retaileraccounts',
            old_name='account_manager',
            new_name='wholesaler_contact',
        ),
    ]
