# Generated by Django 3.1.1 on 2021-02-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0008_auto_20210212_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleproducts',
            name='available_quantity',
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='payment_terms',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('PLACEMENT', 'PLACEMENT')], default='CASH', max_length=100),
        ),
    ]
