# Generated by Django 3.1.1 on 2021-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0008_auto_20210208_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despatches',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DESPATCHED', 'DESPATCHED'), ('RECEIVED', 'RECEIVED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100),
        ),
    ]
