# Generated by Django 3.1.1 on 2021-02-05 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0009_auto_20210205_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='despatchitems',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 5, 19, 49, 20, 36095, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despatchitems',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
