# Generated by Django 3.1.1 on 2021-02-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
        ('wholesales', '0009_auto_20210212_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalevariations',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_purchases', to='drugs.distributor'),
        ),
    ]
