# Generated by Django 3.1.1 on 2021-02-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0009_auto_20210208_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='despatchitems',
            name='wholesale_variation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='despatch_item_variation', to='wholesales.wholesalevariations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despatchitems',
            name='requisition_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_item_requisition', to='wholesales.requisitions'),
        ),
        migrations.AddConstraint(
            model_name='despatchitems',
            constraint=models.UniqueConstraint(fields=('facility', 'despatch', 'requisition_item', 'wholesale_variation'), name='One variation item in despatch'),
        ),
    ]
