# Generated by Django 3.1.1 on 2021-02-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0010_auto_20210208_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despatchitems',
            name='requisition_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_item_requisition', to='wholesales.requisitionitems'),
        ),
    ]
