# Generated by Django 3.1.1 on 2021-02-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0011_auto_20210208_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despatchitems',
            name='quantity_issued',
            field=models.IntegerField(default=0),
        ),
    ]
