# Generated by Django 3.1.1 on 2021-02-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0012_auto_20210208_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wholesalevariations',
            old_name='pack_buying_price',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='wholesalevariations',
            old_name='pack_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='wholesalevariations',
            old_name='pack_selling_price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='wholesaleproducts',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
