# Generated by Django 3.1.1 on 2021-02-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0013_auto_20210209_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalevariations',
            name='batch',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
