# Generated by Django 3.1.1 on 2021-02-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0014_wholesalevariations_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuses',
            name='wholesale_variation',
        ),
        migrations.RemoveField(
            model_name='despatchitems',
            name='wholesale_variation',
        ),
        migrations.RemoveField(
            model_name='discounts',
            name='wholesale_variation',
        ),
        migrations.AddField(
            model_name='bonuses',
            name='wholesale_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_product', to='wholesales.wholesaleproducts'),
        ),
        migrations.AddField(
            model_name='despatchitems',
            name='wholesale_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='despatch_item_product', to='wholesales.wholesaleproducts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discounts',
            name='wholesale_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_product', to='wholesales.wholesaleproducts'),
        ),
    ]
