# Generated by Django 3.1.1 on 2021-02-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0014_auto_20210213_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalevariations',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wholesalevariations',
            name='quantity_issued',
            field=models.IntegerField(default=0),
        ),
    ]
