# Generated by Django 3.1.1 on 2021-02-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0015_auto_20210209_1445'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='requisitionitems',
            constraint=models.UniqueConstraint(fields=('facility', 'requisition', 'wholesale_product'), name='Unique item per requisition'),
        ),
    ]
