# Generated by Django 3.1.1 on 2021-02-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20210212_1641'),
        ('wholesales', '0015_auto_20210213_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalevariations',
            name='product',
            field=models.ForeignKey(default='5584925b-cb9b-46a8-800a-3ffae175380b', on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_variation_product', to='drugs.products'),
            preserve_default=False,
        ),
    ]
