# Generated by Django 3.1.1 on 2021-02-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0016_auto_20210213_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
