# Generated by Django 3.1.1 on 2021-02-10 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
        ('wholesales', '0016_auto_20210209_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_terms', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('PLACEMENT', 'PLACEMENT')], max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('despatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_for_despatch', to='wholesales.despatches')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitionpayments', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despatch_payment_owner', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_payment_method', to='payments.paymentmethods')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RETAILER_CONFIRMED', 'RETAILER CONFIRMED'), ('PROCESSING', 'PROCESSING'), ('PARTIALLY_DISPATCHED', 'PARTIALLY DISPATCHED'), ('FULLY_DISPATCHED', 'FULLY DISPATCHED'), ('CANCELLED', 'CANCELLED'), ('CLOSED', 'CLOSED')], default='PENDING', max_length=100),
        ),
        migrations.DeleteModel(
            name='DespatchPayments',
        ),
    ]
