# Generated by Django 3.1.1 on 2021-02-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('wholesales', '0017_auto_20210210_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionpayments',
            name='despatch',
        ),
        migrations.AddField(
            model_name='requisitionpayments',
            name='requisition',
            field=models.ForeignKey(default='310a1147-11d8-450d-b4f7-663b0446b192', on_delete=django.db.models.deletion.CASCADE, related_name='payment_requisition', to='wholesales.requisitions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisitions',
            name='payment_method',
            field=models.ForeignKey(default='310a1147-11d8-450d-b4f7-663b0446b192', on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods'),
            preserve_default=False,
        ),
    ]
