# Generated by Django 3.1.1 on 2021-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0017_auto_20210213_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitions',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
