# Generated by Django 3.1.1 on 2021-02-10 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('wholesales', '0018_auto_20210210_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionpayments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods'),
        ),
    ]
