# Generated by Django 3.1.1 on 2021-02-13 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0001_initial'),
        ('users', '0001_initial'),
        ('wholesales', '0019_auto_20210213_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_invoiced', models.IntegerField(default=0)),
                ('bonus_quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceitems', to='users.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_type', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('PLACEMENT', 'PLACEMENT')], max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('despatch_confirmed', models.BooleanField(default=False)),
                ('courier_confirmed', models.BooleanField(default=False)),
                ('receipt_confirmed', models.BooleanField(default=False)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_done_by', to='entities.employees')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_owner', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_requisition', to='wholesales.requisitions')),
                ('retail_receipt_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_receipt_by', to=settings.AUTH_USER_MODEL)),
                ('wholesale_despatch_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_despatch_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='requisitionitems',
            name='wholesale_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_item_variation', to='wholesales.wholesalevariations'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_item_invoice', to='wholesales.invoices'),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='wholesale_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_item', to='wholesales.wholesalevariations'),
        ),
    ]
