# Generated by Django 3.1.1 on 2021-02-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0019_auto_20210210_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitions',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
