# Generated by Django 3.1.1 on 2021-02-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0020_requisitions_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionpayments',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requisition', to='wholesales.requisitions'),
        ),
    ]
