# Generated by Django 3.1.1 on 2021-02-14 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0020_auto_20210213_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoices',
            name='wholesale_approved_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_aproved_by', to='users.user'),
            preserve_default=False,
        ),
    ]
