# Generated by Django 3.1.1 on 2021-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0021_auto_20210214_0823'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoices',
            constraint=models.UniqueConstraint(fields=('facility', 'requisition'), name='Unique invoice per requisition'),
        ),
    ]
