# Generated by Django 3.1.1 on 2021-02-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0021_auto_20210210_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despatchitems',
            name='wholesale_product',
        ),
    ]
