# Generated by Django 3.1.1 on 2021-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0023_auto_20210210_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despatchitems',
            name='wholesaler_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
