# Generated by Django 3.1.1 on 2021-02-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0023_auto_20210214_0836'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoiceitems',
            constraint=models.UniqueConstraint(fields=('facility', 'invoice', 'requisition_item'), name='Unique invoice item per invoice'),
        ),
    ]
