# Generated by Django 3.1.1 on 2021-02-10 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0024_auto_20210210_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='despatchitems',
            name='wholesaler_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_confirmed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
