# Generated by Django 3.1.1 on 2021-02-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0024_auto_20210214_0839'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoices',
            name='Unique invoice per requisition',
        ),
        migrations.AddField(
            model_name='invoices',
            name='retailer_account',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_requisition', to='wholesales.retaileraccounts'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='invoices',
            constraint=models.UniqueConstraint(fields=('facility', 'retailer_account', 'requisition'), name='Unique invoice per requisition'),
        ),
    ]
