# Generated by Django 3.1.1 on 2021-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0025_despatchitems_wholesaler_confirmed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despatches',
            old_name='despatch_confirmed',
            new_name='retailer_receipt_confirmed',
        ),
        migrations.RenameField(
            model_name='despatches',
            old_name='receipt_confirmed_by',
            new_name='retailer_receipt_confirmed_by',
        ),
        migrations.RenameField(
            model_name='despatches',
            old_name='receipt_confirmed',
            new_name='wholesaler_despatch_confirmed',
        ),
        migrations.RenameField(
            model_name='despatches',
            old_name='despatch_confirmed_by',
            new_name='wholesaler_despatch_confirmed_by',
        ),
        migrations.RenameField(
            model_name='despatchitems',
            old_name='wholesaler_confirmed',
            new_name='retailer_receipt_confirmed',
        ),
        migrations.RenameField(
            model_name='despatchitems',
            old_name='wholesaler_confirmed_by',
            new_name='wholesaler_despatch_confirmed_by',
        ),
        migrations.AddField(
            model_name='despatchitems',
            name='wholesaler_despatch_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
