# Generated by Django 3.1.1 on 2021-02-14 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('wholesales', '0025_auto_20210214_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_done_by', to='entities.employees'),
        ),
    ]
