# Generated by Django 3.1.1 on 2021-02-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0026_auto_20210210_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='despatchitems',
            name='pack_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
