# Generated by Django 3.1.1 on 2021-02-14 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesales', '0026_auto_20210214_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='retail_receipt_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_receipt_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='wholesale_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_aproved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='wholesale_despatch_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_despatch_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
