# Generated by Django 3.1.1 on 2021-02-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wholesales', '0027_auto_20210214_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='wholesale',
            field=models.ForeignKey(default='49bf8f83-2605-457c-b308-d3378f134636', on_delete=django.db.models.deletion.CASCADE, related_name='invoicing_wholesale', to='users.facility'),
            preserve_default=False,
        ),
    ]
