# Generated by Django 3.1.1 on 2021-02-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0027_despatchitems_pack_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonuses',
            old_name='for_every',
            new_name='bonus_quantity',
        ),
        migrations.RenameField(
            model_name='bonuses',
            old_name='get_free',
            new_name='highest_limit',
        ),
        migrations.AddField(
            model_name='bonuses',
            name='lowest_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
