# Generated by Django 3.1.1 on 2021-02-11 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('wholesales', '0028_auto_20210210_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionVariations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_issued', models.IntegerField(default=0)),
                ('pack_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('batch', models.CharField(blank=True, max_length=140, null=True)),
                ('wholesaler_despatch_confirmed', models.BooleanField(default=False)),
                ('retailer_receipt_confirmed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitionvariations', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_item_owner', to=settings.AUTH_USER_MODEL)),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_item_requisition_item', to='wholesales.requisitionitems')),
                ('wholesale_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_item_variation', to='wholesales.wholesalevariations')),
                ('wholesaler_despatch_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_variation_confirmed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='requisitionvariations',
            constraint=models.UniqueConstraint(fields=('facility', 'requisition_item', 'wholesale_variation'), name='One variation item'),
        ),
    ]
