# Generated by Django 3.1.1 on 2021-02-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0028_invoices_wholesale'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoices',
            name='Unique invoice per requisition',
        ),
        migrations.AddConstraint(
            model_name='invoices',
            constraint=models.UniqueConstraint(fields=('facility', 'wholesale', 'retailer_account', 'requisition'), name='Unique invoice per requisition'),
        ),
    ]
