# Generated by Django 3.1.1 on 2021-02-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0029_auto_20210214_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='courier_comment',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='retailer_comment',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='wholesaler_comment',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
