# Generated by Django 3.1.1 on 2021-02-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0030_auto_20210211_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionvariations',
            name='deficit_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wholesalevariations',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wholesalevariations',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
    ]
