# Generated by Django 3.1.1 on 2021-02-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('Default', 'Default'), ('RetailPharmacy', 'RetailPharmacy'), ('BulkPharmacy', 'BulkPharmacy'), ('Clinic', 'Clinic')], max_length=50),
        ),
    ]
