# Generated by Django 3.1.1 on 2021-01-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadres',
            name='cluster',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('CLERICAL', 'CLERICAL'), ('CONSULTATION', 'CONSULTATION'), ('NURSING', 'NURSING'), ('OTHERS', 'OTHERS'), ('PHARMACY', 'PHARMACY')], default='OTHERS', max_length=20),
        ),
    ]
