# Generated by Django 3.1.1 on 2021-02-19 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210219_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityimage',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegulatorLicence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licence', models.FileField(upload_to=users.models.regulator_licence_upload_to)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(auto_now_add=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulator_licence', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulator_licence_verified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountyPermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licence', models.FileField(upload_to=users.models.county_permit_upload_to)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_permit', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_permit_verified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
