# Generated by Django 3.1.1 on 2021-01-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210113_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='user',
            new_name='owner',
        ),
    ]
