# Generated by Django 3.1.1 on 2021-01-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_enterprises'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprises',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
