# Generated by Django 3.1.1 on 2021-01-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210127_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enterprises',
        ),
    ]
