# Generated by Django 3.1.1 on 2021-02-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210219_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countypermit',
            old_name='licence',
            new_name='county_permit',
        ),
        migrations.RenameField(
            model_name='regulatorlicence',
            old_name='licence',
            new_name='regulator_licence',
        ),
    ]
