# Generated by Django 3.1.1 on 2021-01-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_facilityimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
