# Generated by Django 3.1.1 on 2021-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210220_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('ALL', 'ALL'), ('COURIER', 'COURIER'), ('DOCTOR', 'DOCTOR'), ('NURSE', 'NURSE'), ('PHARMACIST', 'PHARMACIST')], default='ALL', max_length=120),
        ),
    ]
