# Generated by Django 3.1.1 on 2021-01-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_enterprises'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='enterprise',
            field=models.ForeignKey(default='1e416158-a321-4dbd-be27-72fd386fa0cf', on_delete=django.db.models.deletion.CASCADE, related_name='facility_enterprise', to='users.enterprises'),
            preserve_default=False,
        ),
    ]
