# Generated by Django 3.1.1 on 2021-01-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_facility_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='enterprise',
        ),
        migrations.DeleteModel(
            name='Enterprises',
        ),
    ]
