# Generated by Django 3.1.1 on 2021-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210127_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='trial_done',
            field=models.BooleanField(default=False),
        ),
    ]
