# Generated by Django 3.1.1 on 2021-01-27 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalCharges',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentalcharges', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmental_charges_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
