# Generated by Django 3.1.1 on 2021-01-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20210126_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='professional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_professional', to='entities.professionals'),
        ),
    ]
