# Generated by Django 3.1.1 on 2021-01-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_departmentalcharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_professional', to='entities.professionals'),
        ),
    ]
