# Generated by Django 3.1.1 on 2021-01-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20210128_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentalcharges',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='charges',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='entities.departmentalcharges'),
            preserve_default=False,
        ),
    ]
