# Generated by Django 3.1.1 on 2021-01-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20210126_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(default='', max_length=120, unique=True),
            preserve_default=False,
        ),
       
    ]
