# Generated by Django 3.1.1 on 2021-01-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_remove_employees_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
