# Generated by Django 3.1.1 on 2021-01-26 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0004_auto_20210126_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('risk_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('uniform_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.employees')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
