# Generated by Django 3.1.1 on 2021-01-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20210129_0110'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='One department name per facility',
        ),
        migrations.RemoveField(
            model_name='department',
            name='charges',
        ),
        migrations.AddField(
            model_name='departmentalcharges',
            name='department',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='entities.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
