# Generated by Django 3.1.1 on 2021-01-30 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cadres_cluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0006_auto_20210130_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_vacant', models.BooleanField(default=True)),
                ('is_advertised', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('cadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cadres')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='employees',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation', to='entities.designations'),
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
