# Generated by Django 3.1.1 on 2021-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20210129_0116'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('facility', 'title'), name='Unique department title in each facility'),
        ),
    ]
