# Generated by Django 3.1.1 on 2021-01-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20210130_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='is_vacant',
        ),
    ]
