# Generated by Django 3.1.1 on 2021-01-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_remove_jobs_is_vacant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='designation',
            new_name='job',
        ),
        migrations.AddField(
            model_name='employees',
            name='professional',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employee_professional', to='entities.professionals'),
            preserve_default=False,
        ),
    ]
