# Generated by Django 3.1.1 on 2021-01-31 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20210130_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='entities.department'),
            preserve_default=False,
        ),
    ]
