# Generated by Django 3.1.1 on 2021-02-12 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import retailers.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
        ('payments', '0001_initial'),
        ('drugs', '0001_initial'),
        ('wholesales', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Forwarded', 'Forwarded'), ('Quoted', 'Quoted'), ('Confirmed', 'Confirmed'), ('Partially Dispensed', 'Partally Dispensed'), ('Fully Dispensed', 'Fully Dispensed')], default='Forwarded', max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_prescription_prescription', to='consultations.prescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_confirmed', models.BooleanField(default=False)),
                ('pharmacist_confirmed', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_facility', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_confirmed', models.BooleanField(default=False)),
                ('pharmacist_confirmed', models.BooleanField(default=False)),
                ('pharmacist_processing', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionquote', to='users.facility')),
                ('forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_quote_forward', to='retailers.forwards')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_quote_quoted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Jambopay', 'Jambopay'), ('Mpesa', 'Mpesa'), ('Visa', 'Visa')], max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionsale', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.prescriptionquote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailproducts', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_products_product', to='drugs.products')),
            ],
        ),
        migrations.CreateModel(
            name='RetailVariations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('units_per_pack', models.IntegerField(default=0)),
                ('pack_quantity', models.IntegerField(default=0)),
                ('pack_buying_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pack_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_quantity', models.IntegerField(default=0)),
                ('unit_buying_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_variation_facility', to='users.facility')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailvariations', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('retail_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.retailproducts')),
                ('wholesale_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_product_images', to='wholesales.wholesaleproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailProductPhotos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=retailers.models.retail_product_image_upload_to)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailproductphotos', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('retail_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_product_images', to='retailers.retailproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_required', models.IntegerField(default=0)),
                ('quantity_dispensed', models.IntegerField(default=0)),
                ('quantity_pending', models.IntegerField(default=0)),
                ('pharmacist_instructions', models.TextField(blank=True, null=True)),
                ('dose_divisible', models.BooleanField(default=True)),
                ('item_accepted', models.BooleanField(default=True)),
                ('fully_dispensed', models.BooleanField(default=False)),
                ('client_comment', models.TextField(blank=True, null=True)),
                ('client_confirmed', models.BooleanField(default=False)),
                ('pharmacist_confirmed', models.BooleanField(default=False)),
                ('pharmacist_processing', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteitem', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item', to='consultations.prescriptionitem')),
                ('prescription_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retailers.prescriptionquote')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_item_processed_by', to=settings.AUTH_USER_MODEL)),
                ('retail_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_item_retail_variation', to='retailers.retailproducts')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionsaleitem', to='users.facility')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_quote_item', to='retailers.quoteitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.prescriptionsale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=120)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_facility', to='users.facility')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='retailers.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_payment_owner', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('client_confirmed', models.BooleanField(default=False)),
                ('pharmacist_confirmed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.facility')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quote_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retailers.quoteitem')),
                ('retail_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.retailvariations')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_prescription_quote', to='retailers.prescriptionquote'),
        ),
        migrations.CreateModel(
            name='CounterSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countersaleitem', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Jambopay', 'Jambopay'), ('Mpesa', 'Mpesa'), ('Visa', 'Visa')], max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countersale', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='retailproducts',
            constraint=models.UniqueConstraint(fields=('facility', 'product'), name='one product per facility'),
        ),
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together={('prescription_quote', 'prescription_item', 'retail_product')},
        ),
        migrations.AddConstraint(
            model_name='prescriptionquote',
            constraint=models.UniqueConstraint(fields=('facility', 'forward'), name='One quote per prescription'),
        ),
        migrations.AddConstraint(
            model_name='pharmacypayments',
            constraint=models.UniqueConstraint(fields=('facility', 'order'), name='One payment per facility per order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('facility', 'quote_item', 'order', 'retail_variation'), name='One quote item in order'),
        ),
    ]
