# Generated by Django 3.1.1 on 2021-02-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailvariations',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_variation_facility', to='users.facility'),
        ),
    ]
