# Generated by Django 3.1.1 on 2021-02-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20210212_1641'),
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailvariations',
            name='wholesale_product',
        ),
        migrations.AddField(
            model_name='retailvariations',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_product_images', to='drugs.products'),
        ),
    ]
