# Generated by Django 3.1.1 on 2021-02-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('retailers', '0002_auto_20210213_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailproducts',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='retailproducts',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='retailproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='retailvariations',
            name='retail_product',
        ),
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together={('prescription_quote', 'prescription_item')},
        ),
        migrations.DeleteModel(
            name='RetailProductPhotos',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='retail_product',
        ),
        migrations.DeleteModel(
            name='RetailProducts',
        ),
    ]
