# Generated by Django 3.1.1 on 2021-02-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0002_auto_20210210_1728'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retailproducts',
            name='one product per facility',
        ),
    ]
