# Generated by Django 3.1.1 on 2021-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0002_retailvariations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='retailproducts',
            constraint=models.UniqueConstraint(fields=('facility', 'product'), name='one product per facility'),
        ),
    ]
