# Generated by Django 3.1.1 on 2021-02-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0003_auto_20210206_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailvariations',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retailvariations',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
