# Generated by Django 3.1.1 on 2021-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0003_auto_20210210_1733'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='retailproducts',
            constraint=models.UniqueConstraint(fields=('facility', 'product'), name='one product per facility'),
        ),
    ]
