# Generated by Django 3.1.1 on 2021-02-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20210212_1641'),
        ('retailers', '0004_remove_retailvariations_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailvariations',
            name='product',
            field=models.ForeignKey(default='088aab8b-7ba9-4384-b374-33687658aac9', on_delete=django.db.models.deletion.CASCADE, related_name='retail_variation_product', to='drugs.products'),
            preserve_default=False,
        ),
    ]
