# Generated by Django 3.1.1 on 2021-02-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20210212_1641'),
        ('retailers', '0005_retailvariations_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailvariations',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesaler_invoice', to='drugs.products'),
        ),
    ]
