# Generated by Django 3.1.1 on 2021-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0006_retailvariations_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailvariations',
            name='in_placement',
            field=models.BooleanField(default=False),
        ),
    ]
