# Generated by Django 3.1.1 on 2021-02-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0007_retailvariations_in_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='retail_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_item_retail_variation', to='retailers.retailvariations'),
        ),
    ]
