# Generated by Django 3.1.1 on 2021-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardprescription',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
