# Generated by Django 3.1.1 on 2021-01-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210127_0117'),
        ('subscriptions', '0002_auto_20210127_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='facility',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='users.facility'),
            preserve_default=False,
        ),
    ]
