# Generated by Django 3.1.1 on 2021-01-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210127_0117'),
        ('subscriptions', '0003_plan_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.facility'),
        ),
    ]
