# Generated by Django 3.1.1 on 2021-01-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210127_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
