# Generated by Django 3.1.1 on 2021-01-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_delete_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
