# Generated by Django 3.1.1 on 2021-01-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210126_2146'),
        ('subscriptions', '0007_plan_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods'),
            preserve_default=False,
        ),
    ]
