# Generated by Django 3.1.1 on 2021-01-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20210128_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayments',
            name='subscription_created',
            field=models.BooleanField(default=False),
        ),
    ]
