# Generated by Django 3.1.1 on 2021-01-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscriptionpayments_subscription_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='initiated_on',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='terminated_on',
            new_name='start_date',
        ),
    ]
