# Generated by Django 3.1.1 on 2020-12-22 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_auto_20201221_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='owner',
            field=models.ForeignKey(default='c9564ed0-a367-451d-bd9a-15ea3f55eac2', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
