# Generated by Django 3.1.1 on 2021-01-21 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('drugs', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=120, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_dependant', to='users.dependant')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionitem', to='users.facility')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_frequency', to='drugs.frequency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_posology', to='drugs.posology')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_preparation', to='drugs.preparation')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_prescription', to='consultations.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_product', to='drugs.product')),
            ],
            options={
                'unique_together': {('prescription', 'preparation', 'product')},
            },
        ),
    ]
