# Generated by Django 3.1.1 on 2021-02-11 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugs', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('allergy_category', models.CharField(choices=[('Drug Allergy', 'Drug Allergy'), ('Food Allergy', 'Food Allergy'), ('Environmental Allergy', 'Environmental Allargy')], max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentConsultations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_complaint', models.TextField()),
                ('complaint_duration_length', models.IntegerField(default=0)),
                ('complaint_duration_unit', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Years', 'Years')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('onset', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=300)),
                ('aggravating_factors', models.CharField(max_length=300)),
                ('previous_treatment', models.CharField(max_length=300)),
                ('uses_alcohol', models.BooleanField(default=False)),
                ('uses_tobbaco', models.BooleanField(default=False)),
                ('is_married', models.BooleanField(default=False)),
                ('current_occupation', models.TextField()),
                ('current_diagnosis', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('allergies', models.ManyToManyField(to='consultations.Allergy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('narrative', models.CharField(max_length=300)),
                ('reference', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=120)),
                ('appointment_created', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_dependant', to='users.dependant')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentpayments', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=120, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_dependant', to='users.dependant')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.appointmentconsultations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(default=None)),
                ('end', models.DateTimeField(default=None)),
                ('is_available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_employee', to='entities.employees')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionitem', to='users.facility')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_frequency', to='drugs.frequency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_posology', to='drugs.posology')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_prescription', to='consultations.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_product', to='drugs.products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('ATTENDED', 'ATTENDED'), ('ABSCONDED', 'ABSCONDED'), ('RESCHEDULED', 'RESCHEDULED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('appointment_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slot', to='consultations.appointmentpayments')),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dependant')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointmentpayments',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.slots'),
        ),
        migrations.AddField(
            model_name='appointmentconsultations',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultation_appointment', to='consultations.appointments'),
        ),
        migrations.AddField(
            model_name='appointmentconsultations',
            name='current_medication',
            field=models.ManyToManyField(to='drugs.Generic'),
        ),
        migrations.AddField(
            model_name='appointmentconsultations',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentconsultations', to='users.facility'),
        ),
        migrations.AddField(
            model_name='appointmentconsultations',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='appointmentpayments',
            constraint=models.UniqueConstraint(fields=('facility', 'dependant', 'slot', 'reference'), name='One payment per appointment'),
        ),
    ]
