# Generated by Django 3.1.1 on 2021-01-26 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugs', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultation_dependant', to='users.dependant')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientConsultations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_complaint', models.TextField()),
                ('complaint_duration_length', models.IntegerField(default=0)),
                ('complaint_duration_unit', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Years', 'Years')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('onset', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=300)),
                ('aggravating_factors', models.CharField(max_length=300)),
                ('previous_treatment', models.CharField(max_length=300)),
                ('uses_alcohol', models.BooleanField(default=False)),
                ('uses_tobbaco', models.BooleanField(default=False)),
                ('is_married', models.BooleanField(default=False)),
                ('current_occupation', models.TextField()),
                ('current_diagnosis', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('allergies', models.ManyToManyField(to='users.Allergy')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultation_appointment', to='consultations.appointments')),
                ('current_medication', models.ManyToManyField(to='drugs.Generic')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientconsultations', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=120, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_dependant', to='users.dependant')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.patientconsultations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(default=None)),
                ('end', models.DateTimeField(default=None)),
                ('is_available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointments',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slot', to='consultations.slots'),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionitem', to='users.facility')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_frequency', to='drugs.frequency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_posology', to='drugs.posology')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_preparation', to='drugs.preparation')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_prescription', to='consultations.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item_product', to='drugs.product')),
            ],
            options={
                'unique_together': {('prescription', 'preparation', 'product')},
            },
        ),
        migrations.AddConstraint(
            model_name='appointments',
            constraint=models.UniqueConstraint(fields=('slot', 'dependant'), name='One patient per appointment slot'),
        ),
    ]
