# Generated by Django 3.1.1 on 2021-01-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('consultations', '0001_initial'),
    ]

    