# Generated by Django 3.1.1 on 2021-01-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
