# Generated by Django 3.1.1 on 2021-02-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptionitem',
            unique_together=set(),
        ),
    ]
