# Generated by Django 3.1.1 on 2021-01-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '__first__'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptionitem',
            unique_together={('prescription', 'preparation', 'product')},
        ),
    ]
