# Generated by Django 3.1.1 on 2021-01-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('consultations', '0002_auto_20210126_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='slot_employee', to='entities.employees'),
            preserve_default=False,
        ),
    ]
