# Generated by Django 3.1.1 on 2021-01-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_auto_20210126_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='employee',
        ),
    ]
