# Generated by Django 3.1.1 on 2021-01-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_auto_20210121_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
