# Generated by Django 3.1.1 on 2021-01-30 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('consultations', '0003_auto_20210129_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='dependant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.dependant'),
            preserve_default=False,
        ),
    ]
