# Generated by Django 3.1.1 on 2021-01-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_slots_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ATTENDED', 'ATTENDED'), ('ABSCONDED', 'ABSCONDED'), ('RESCHEDULED', 'RESCHEDULED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100),
        ),
    ]
