# Generated by Django 3.1.1 on 2021-01-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_remove_slots_employee'),
        ('consultations', '0004_appointments_status'),
    ]

    operations = [
    ]
