# Generated by Django 3.1.1 on 2021-01-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_auto_20210121_0524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptionitem',
            unique_together=set(),
        ),
    ]
