# Generated by Django 3.1.1 on 2021-01-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_appointments_dependant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentconsultations',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='consultations.Allergy'),
        ),
    ]
