# Generated by Django 3.1.1 on 2021-01-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
        ('consultations', '0005_auto_20210121_0826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptionitem',
            unique_together={('prescription', 'preparation', 'product')},
        ),
    ]
