# Generated by Django 3.1.1 on 2021-01-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_auto_20210128_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentpayments',
            old_name='subscription_created',
            new_name='appointment_created',
        ),
    ]
