# Generated by Django 3.1.1 on 2021-01-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_auto_20210130_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentconsultations',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointmentconsultations',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
