# Generated by Django 3.1.1 on 2021-01-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_auto_20210129_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('ATTENDED', 'ATTENDED'), ('ABSCONDED', 'ABSCONDED'), ('RESCHEDULED', 'RESCHEDULED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100),
        ),
    ]
