# Generated by Django 3.1.1 on 2021-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_auto_20210129_0112'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointmentpayments',
            constraint=models.UniqueConstraint(fields=('facility', 'dependant', 'slot'), name='One payment per appointment'),
        ),
    ]
