# Generated by Django 3.1.1 on 2021-02-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20210201_0340'),
        ('consultations', '0008_auto_20210130_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentconsultations',
            name='allergies',
            field=models.ManyToManyField(to='consultations.Allergy'),
        ),
        migrations.AlterField(
            model_name='appointmentconsultations',
            name='current_medication',
            field=models.ManyToManyField(to='drugs.Generic'),
        ),
    ]
