# Generated by Django 3.1.1 on 2021-01-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210126_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
