# Generated by Django 3.1.1 on 2021-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210127_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
