# Generated by Django 3.1.1 on 2021-01-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethods_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
