# Generated by Django 3.1.1 on 2021-02-03 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '__first__'),
        ('inventory', '0001_initial'),
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                       
                                        editable=False, primary_key=True, serialize=False)),
                ('client_confirmed', models.BooleanField(default=False)),
                ('pharmacist_confirmed', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                 
                                                            related_name='cart_facility', to='users.facility')),
                ('owner', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('client_confirmed', models.BooleanField(default=False)),
                ('pharmacist_confirmed', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='prescriptionquote', to='users.facility')),
                ('owner', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True,
                                                     on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods')),
                ('quoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='prescription_quote_quoted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,

                                                                               editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(
                    
                    decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[
                 
                 ('Cash', 'Cash'), ('Jambopay', 'Jambopay'), ('Mpesa', 'Mpesa'), ('Visa', 'Visa')], max_length=100)),
                ('reference_number', models.CharField(
                    
                    blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              
                                               related_name='prescriptionsale', to='users.facility')),
                ('owner', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to='pharmacies.prescriptionquote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('quantity_required', models.IntegerField(default=0)),
                ('quantity_dispensed', models.IntegerField(default=0)),
                ('quantity_pending', models.IntegerField(default=0)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('dose_divisible', models.BooleanField(default=True)),
                ('item_accepted', models.BooleanField(default=True)),
                ('fully_dispensed', models.BooleanField(default=False)),
                ('client_comment', models.TextField(blank=True, null=True)),
                ('client_confirmed', models.BooleanField(default=False)),
                ('pharmacist_confirmed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              
                                               related_name='quoteitem', to='users.facility')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='quote_item_inventory', to='inventory.inventory')),
                ('owner', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             
                                                                  related_name='prescription_item', to='consultations.prescriptionitem')),
                ('prescription_quote', models.ForeignKey(blank=True, null=True,
                                                        
                                                         on_delete=django.db.models.deletion.CASCADE, to='pharmacies.prescriptionquote')),
                ('quoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='quote_item_quoted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('prescription_quote', 'prescription_item', 'inventory')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                              
                                                 editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(
                    
                    decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                
                                                             related_name='prescriptionsaleitem', to='users.facility')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                  
                                                                   related_name='sale_quote_item', to='pharmacies.quoteitem')),
                ('owner', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to='pharmacies.prescriptionsale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(
                    blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), (
                    'SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=120)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='payment_facility', to='users.facility')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='payment_order', to='pharmacies.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='pharmacy_payment_owner', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                       
                                        editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('client_confirmed', models.BooleanField(default=False)),
                ('pharmacist_confirmed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to='users.facility')),
                ('order', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to='pharmacies.order')),
                ('owner', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quote_item', models.ForeignKey(blank=True, null=True,
                                                
                                                 on_delete=django.db.models.deletion.CASCADE, to='pharmacies.quoteitem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   
                                    related_name='cart_prescription_quote', to='pharmacies.prescriptionquote'),
        ),

        migrations.CreateModel(
            name='CounterSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,

                                                                               editable=False, primary_key=True, serialize=False)),
                ('client_phone', models.CharField(
                    
                    blank=True, max_length=30, null=True)),
                ('cost', models.DecimalField(
                    
                    decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              
                                               related_name='countersaleitem', to='users.facility')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='sale_item', to='inventory.inventory')),
                ('owner', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,

                                                                               editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(
                    
                    decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[
                 
                 ('Cash', 'Cash'), ('Jambopay', 'Jambopay'), ('Mpesa', 'Mpesa'), ('Visa', 'Visa')], max_length=100)),
                ('reference_number', models.CharField(
                    
                    blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              
                                               related_name='countersale', to='users.facility')),
                ('owner', models.ForeignKey(
                    
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='prescriptionquote',
            constraint=models.UniqueConstraint(
                
                fields=('facility', 'prescription'), name='One quote per prescription'),
        ),
        migrations.AddConstraint(
            model_name='pharmacypayments',
            constraint=models.UniqueConstraint(
                fields=('facility', 'order'), name='One payment per facility per order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(
                
                fields=('facility', 'quote_item'), name='One quote item in order'),
        ),

    ]
