# Generated by Django 3.1.1 on 2021-01-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionquote',
            name='pharmacist_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
