# Generated by Django 3.1.1 on 2021-01-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionquote',
            name='prescription',
        ),
    ]
