# Generated by Django 3.1.1 on 2021-01-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_prescriptionquote_pharmacist_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionquote',
            name='prescription_cost',
        ),
    ]
