# Generated by Django 3.1.1 on 2021-02-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_auto_20210202_2330'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='forwards',
            name='forward prescription to pharmacy once',
        ),
    ]
