# Generated by Django 3.1.1 on 2021-01-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_auto_20210126_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
