# Generated by Django 3.1.1 on 2021-01-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('pharmacies', '0002_remove_prescriptionquote_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionquote',
            name='prescription',
            field=models.ForeignKey(default='879d2f7a-a8c3-433f-b144-8426032c5332', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_quote_prescription', to='consultations.prescription'),
            preserve_default=False,
        ),
    ]
