# Generated by Django 3.1.1 on 2021-01-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('consultations', '0001_initial'),
        ('pharmacies', '0003_prescriptionquote_prescription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together={('prescription', 'prescription_item', 'quoted_item')},
        ),
    ]
