# Generated by Django 3.1.1 on 2021-01-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_remove_prescriptionquote_prescription_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='item_cost',
        ),
    ]
