# Generated by Django 3.1.1 on 2021-02-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_auto_20210202_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionquote',
            name='forward',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_quote_forward', to='pharmacies.forwards'),
            preserve_default=False,
        ),
    ]
