# Generated by Django 3.1.1 on 2021-02-03 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pharmacies', '0004_prescriptionquote_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_item_inventory', to='inventory.variations'),
        ),
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together={('prescription_quote', 'prescription_item', 'variation')},
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='inventory',
        ),
    ]
