# Generated by Django 3.1.1 on 2021-01-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pharmacies', '0004_auto_20210121_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteitem',
            old_name='prescription',
            new_name='prescription_quote',
        ),
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together={('prescription_quote', 'prescription_item', 'quoted_item')},
        ),
    ]
