# Generated by Django 3.1.1 on 2021-02-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('pharmacies', '0005_auto_20210131_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionquote',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods'),
        ),
    ]
