# Generated by Django 3.1.1 on 2021-02-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_auto_20210203_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionquote',
            old_name='quoted_by',
            new_name='processed_by',
        ),
        migrations.AddField(
            model_name='prescriptionquote',
            name='pharmacist_processing',
            field=models.BooleanField(default=False),
        ),
    ]
