# Generated by Django 3.1.1 on 2021-01-22 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_auto_20210121_0828'),
        ('pharmacies', '0006_auto_20210121_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionquote',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_quote_prescription', to='consultations.prescription'),
        ),
    ]
