# Generated by Django 3.1.1 on 2021-02-03 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacies', '0006_auto_20210203_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='quoted_by',
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='pharmacist_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_item_processed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
