# Generated by Django 3.1.1 on 2021-02-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0007_auto_20210203_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteitem',
            old_name='instructions',
            new_name='pharmacist_instructions',
        ),
    ]
