# Generated by Django 3.1.1 on 2021-01-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('pharmacies', '0007_auto_20210121_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionquote',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_quote_prescription', to='clients.forwardprescription'),
        ),
    ]
