# Generated by Django 3.1.1 on 2021-02-01 07:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_cadres_cluster'),
        ('pharmacies', '0007_auto_20210131_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PharmacyPayment',
            new_name='PharmacyPayments',
        ),
    ]
