# Generated by Django 3.1.1 on 2021-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0008_auto_20210203_0335'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='One quote item in order',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('facility', 'quote_item', 'order'), name='One quote item in order'),
        ),
    ]
