# Generated by Django 3.1.1 on 2021-02-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('pharmacies', '0008_auto_20210131_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacypayments',
            name='payment_method',
            field=models.ForeignKey(default='6d83aeb7-b44b-4ac6-b985-dbd3db314bf2', on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethods'),
            preserve_default=False,
        ),
    ]
