# Generated by Django 3.1.1 on 2021-01-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0008_auto_20210121_2359'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prescriptionquote',
            constraint=models.UniqueConstraint(fields=('facility', 'prescription'), name='One quote per prescription'),
        ),
    ]
