# Generated by Django 3.1.1 on 2021-02-01 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacies', '0009_pharmacypayments_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='quoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_item_quoted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
