# Generated by Django 3.1.1 on 2021-02-01 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacies', '0010_quoteitem_quoted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionquote',
            name='quoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_quote_quoted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
