# Generated by Django 3.1.1 on 2021-01-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pharmacies', '0010_auto_20210122_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='quoted_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation_receipt', to='inventory.variationreceipt'),
        ),
    ]
