# Generated by Django 3.1.1 on 2021-01-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_auto_20210121_0828'),
        ('inventory', '0001_initial'),
        ('pharmacies', '0011_auto_20210122_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteitem',
            old_name='quoted_item',
            new_name='variation_item',
        ),
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together={('prescription_quote', 'prescription_item', 'variation_item')},
        ),
    ]
