# Generated by Django 3.1.1 on 2021-01-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_auto_20210121_0828'),
        ('pharmacies', '0012_auto_20210122_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_item', to='consultations.prescriptionitem'),
        ),
    ]
