# Generated by Django 3.1.1 on 2021-01-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0013_auto_20210122_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='prescription_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacies.prescriptionquote'),
        ),
    ]
