# Generated by Django 3.1.1 on 2021-01-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0014_auto_20210122_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='dose_divisible',
            field=models.BooleanField(default=True),
        ),
    ]
