# Generated by Django 3.1.1 on 2021-01-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0015_quoteitem_dose_divisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='item_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
