# Generated by Django 3.1.1 on 2021-01-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0016_quoteitem_item_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='client_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
