# Generated by Django 3.1.1 on 2021-01-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0017_quoteitem_client_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='fully_dispensed',
            field=models.BooleanField(default=False),
        ),
    ]
