# Generated by Django 3.1.1 on 2021-01-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0021_remove_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
