# Generated by Django 3.1.1 on 2021-01-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0023_auto_20210123_2132'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('facility', 'quote_item'), name='One quote item in order'),
        ),
    ]
