# Generated by Django 3.1.1 on 2021-01-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0024_auto_20210123_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default='64330153-80fc-4ab5-8146-2cc89e54ddbc', on_delete=django.db.models.deletion.CASCADE, to='pharmacies.order'),
            preserve_default=False,
        ),
    ]
