# Generated by Django 3.1.1 on 2021-01-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0025_auto_20210123_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_open',
            new_name='is_confirmed',
        ),
    ]
