# Generated by Django 3.1.1 on 2021-01-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0026_auto_20210123_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('MPESA', 'MPESA'), ('AIRTEL MONEY', 'AIRTEL MONEY'), ('EQUITEL', 'EQUITEL'), ('JAMBOPAY WALLET', 'JAMBOPAY WALLET'), ('VISA', 'VISA')], default='CASH', max_length=120),
            preserve_default=False,
        ),
    ]
