# Generated by Django 3.1.1 on 2021-01-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0028_transaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('facility', 'order'), name='One transation per facility per order'),
        ),
    ]
