# Generated by Django 3.1.1 on 2021-01-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0029_auto_20210124_0053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
