# Generated by Django 3.1.1 on 2021-01-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0032_auto_20210124_0101'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='One payment per facility per order',
        ),
    ]
