# Generated by Django 3.1.1 on 2021-01-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0033_auto_20210124_0125'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('facility', 'order'), name='One payment per facility per order'),
        ),
    ]
